launch:
  ros__parameters:
    joy: true
    icart: false

joy_node:
  ros__parameters:
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_twist_joy_node:
  ros__parameters:
    require_enable_button: true
    enable_button: 4
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 1.0
